### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by eleanorscott01** [JackapakaDan/OOP-assessment#2]
Your code is easy to read and has a good amount of comments describing the process and what your code is doing although there are a lot of if statements towards the end of the code. This is still good as the code runs however maybe there is a more efficient way of implementing returning the card values.  Is there another way you could use instead of if statements? 

The error handling was implemented very well in this program when it presents errors if the input is not correct, that was a great addition to the program and it is interesting on how it was implemented.

Loops have been used in this code which have been used effectively and is a good way to iterate through items. However, for the type of program you are trying to create, for loops might work better. Would you try implementing for loops into your code?

Putting all of your code in one file makes it much more readable and easier to understand what you were trying to do. Would you use multiple files in future projects or would you keep all of your code in one file?

Overall your code runs well and it has a lot of elements that are good such as error handling and user input, it was interesting to review your code and see your approach!

**Comment by JackapakaDan** [comment]
Hi Eleanor,

1. I could use enums, but I've never learnt how to use them, so this will be something I will look to add in future assignments. 

2. The error handling was achieved by using many 'catch' statements, meaning that each error can have a unique message.

3. I will implement for loops in the future, now I understand what each part of the for loop means.

4. In the future I will add multiple files, especially for larger projects, like Unity.

Thank you so much for this helpful feedback!
